app_name: Today
email: hello@danhayes.me
contact_url: https://danhayes.me
github_url: https://github.com/daniel-hayes/today
releases_url: https://github.com/daniel-hayes/today/releases/
description: >-
  A simple, customizable, todo list that clears itself every 24 hours, allowing you to focus on the daily tasks that matter.
github_username: daniel-hayes
logo: icon.png

sass:
  style: compressed
